In [1]:
from FFT import *
import numpy as np
from fxpmath import Fxp
from test import *
from FFT import *

In [2]:
INT=4
DEC=4
N=32

In [4]:
d=RandomBinary(N=40,m=8,INT=INT,DEC=DEC,Th=1)


In [11]:
c=1
d=RandomBinary(N=2*N*c,m=INT+DEC,INT=INT, DEC=DEC, Th=1).reshape([c,N,2])
shape=d.shape
d=d.ravel()

d=np.array(list(map(float,  Fxp(list('0b'+d), True, INT+DEC, DEC)()  )) ) 
d=d.reshape(shape)
d


array([[[ 0.25  , -0.125 ],
        [-0.625 ,  0.375 ],
        [-0.625 ,  0.    ],
        [-0.3125, -0.5   ],
        [ 0.5   ,  0.125 ],
        [ 0.625 , -0.125 ],
        [ 0.3125,  0.1875],
        [-1.    ,  0.6875],
        [-0.0625, -0.4375],
        [ 0.    ,  0.6875],
        [ 0.4375, -0.375 ],
        [ 0.1875, -0.0625],
        [-0.625 ,  0.0625],
        [-0.75  , -0.75  ],
        [-0.1875, -0.6875],
        [-0.125 , -0.5   ],
        [-0.375 ,  0.625 ],
        [ 0.4375, -0.9375],
        [ 0.0625, -0.0625],
        [ 0.1875, -1.    ],
        [ 0.3125, -0.3125],
        [ 0.9375, -0.875 ],
        [-0.875 , -0.75  ],
        [ 0.0625, -0.125 ],
        [ 0.875 , -0.75  ],
        [ 0.4375,  0.4375],
        [ 0.125 , -0.8125],
        [ 0.75  ,  0.5   ],
        [-0.125 , -0.5   ],
        [-0.9375,  0.9375],
        [-0.875 , -0.9375],
        [ 1.    , -0.4375]]])

In [ ]:


shape=d.shape
d=d.ravel()
d=np.array(map(float,  Fxp(list('0b'+d), True, INT+DEC, DEC)()  ))
d=d.reshape(shape)

In [4]:
a=FilterBinary2Dec_Hex(RandomBinary(N=40,m=8),INT=4,DEC=4)

In [5]:
[i for i in range(5) if i>3 or i<1]

[0, 4]

In [6]:
[*1,2,3]

TypeError: 'int' object is not iterable

In [11]:
[*[1,2,*[5],3],4,5]

[1, 2, 5, 3, 4, 5]

In [29]:
[*np.array(([1,2,3],[4,5,6])).T ]

[array([1, 4]), array([2, 5]), array([3, 6])]

In [35]:
np.array([*np.array([1,2,3]) , *np.array([4,5,6])])

array([1, 2, 3, 4, 5, 6])

In [46]:
[*list(zip([1,2,3],[4,5,6]))]

[(1, 4), (2, 5), (3, 6)]

In [50]:
np.array([[1,2,3],[4,5,6]]).T.T.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [25]:
['osama']+np.array(['asd','dfgre'],dtype=object)

array(['osamaasd', 'osamadfgre'], dtype=object)